kind: pipeline
type: docker
name: nemu

steps:
- name: cmake
  image: grafin1992/nemu-ci:v1.1
  volumes:
  - name: cache
    path: /build

  commands:
  - mkdir build && cd build
  - cmake ../ -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON

  depends_on:
  - clone

  when:
    branch:
    - master

- name: codeql
  image: grafin1992/nemu-ci:v1.1
  volumes:
  - name: cache
    path: /build
  environment:
    GITHUB_TOKEN:
      from_secret: github_token

  commands:
  - /codeql/codeql database create lgtm
  - /codeql/codeql database analyze lgtm --format=sarif-latest \
    --sarif-category=cpp --output=./codeql-lgtm.sarif cpp-lgtm.qls
  - /codeql/codeql github upload-results --repository="${DRONE_REPO}" \
    --ref="${DRONE_COMMIT_REF}" --commit="${DRONE_COMMIT_SHA}" \
    --sarif=./codeql-lgtm.sarif

  depends_on:
  - clone

  when:
    branch:
    - master

- name: cppcheck
  image: grafin1992/nemu-ci:v1.1
  volumes:
  - name: cache
    path: /build

  commands:
  - cd build
  - cppcheck --error-exitcode=42 --enable=all --inline-suppr ../src

  depends_on:
  - cmake

- name: codespell
  image: grafin1992/nemu-ci:v1.1
  volumes:
  - name: cache
    path: /build

  commands:
  - cd build
  - codespell -q 3 -L 'fo,ser,ans,chello' \
    -S "./lgtm,./_lgtm_detected_source_root" ../*

  depends_on:
  - cmake

- name: build
  image: grafin1992/nemu-ci:v1.1
  volumes:
  - name: cache
    path: /build

  commands:
  - cd build
  - make

  depends_on:
  - cmake

volumes:
- name: cache
  temp: {}
