kind: pipeline
name: nemu

steps:
- name: build
  image: grafin1992/nemu-ci:v1.0
  commands:
  - mkdir build && cd build
  - cmake ../ -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON
  - cppcheck --error-exitcode=42 --enable=all --inline-suppr ../src
  - codespell -q 3 -L 'fo,ser,ans,chello' ../*
  - make
  when:
    branch:
    - master
