kind: pipeline
type: docker
name: nemu

steps:
- name: cmake
  image: grafin1992/nemu-ci:v1.1

  commands:
  - mkdir build && cd build
  - cmake -G Ninja ../
    -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON
    -DNM_WITH_REMOTE=ON -DNM_WITH_UNICODE_GLYPHS=ON

  depends_on:
  - clone

  when:
    branch:
    - master

- name: codeql
  image: grafin1992/nemu-ci:v1.1
  environment:
    GITHUB_TOKEN:
      from_secret: github_token

  commands:
  - /codeql/codeql database create lgtm --language=cpp
  - /codeql/codeql database analyze lgtm --format=sarif-latest
    --output=./codeql-lgtm.sarif cpp-lgtm.qls
  - /codeql/codeql github upload-results --repository="${DRONE_REPO}"
    --ref="${DRONE_COMMIT_REF}" --commit="${DRONE_COMMIT_SHA}"
    --sarif=./codeql-lgtm.sarif

  depends_on:
  - clone

  when:
    branch:
    - master

- name: cppcheck
  image: grafin1992/nemu-ci:v1.1
  environment:
    GITHUB_TOKEN:
      from_secret: github_token

  commands:
  - cd /sarif-multitool
  - cppcheck --enable=all --suppress=missingIncludeSystem --xml
    --output-file=./cppcheck.xml /drone/src/src
  - npx "@microsoft/sarif-multitool" convert ./cppcheck.xml
    --tool CppCheck --output ./cppcheck.sarif -m --force
  - npx "@microsoft/sarif-multitool" rebaseuri ./cppcheck.sarif
    --base-path-value "file:///drone/src" --base-path-token %SRCROOT% -o ./
    -m --force
  - /codeql/codeql github upload-results --repository="${DRONE_REPO}"
    --ref="${DRONE_COMMIT_REF}" --commit="${DRONE_COMMIT_SHA}"
    --sarif=./cppcheck-rebased.sarif

  depends_on:
  - clone

- name: codespell
  image: grafin1992/nemu-ci:v1.1

  commands:
#  - codespell -q 3 -L 'fo,ser,ans,chello'
#    --skip="../lgtm,../_lgtm_detected_source_root" ./
  - ./ci/codespell-sarif.py -o ./codespell.sarif
  - /codeql/codeql github upload-results --repository="${DRONE_REPO}"
    --ref="${DRONE_COMMIT_REF}" --commit="${DRONE_COMMIT_SHA}"
    --sarif=./codespell.sarif

  depends_on:
  - clone

- name: build
  image: grafin1992/nemu-ci:v1.1

  commands:
  - cd build
  - ninja

  depends_on:
  - cmake
