kind: pipeline
type: docker
name: nemu

steps:
- name: cmake
  image: grafin1992/nemu-ci:v1.0
  volumes:
  - name: cache
    path: /build

  commands:
  - mkdir build && cd build
  - cmake ../ -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON

  when:
    branch:
    - master

- name: cppcheck
  image: grafin1992/nemu-ci:v1.0
  volumes:
  - name: cache
    path: /build

  commands:
  - cd build
  - cppcheck --error-exitcode=42 --enable=all --inline-suppr ../src

  depends_on:
  - cmake

- name: codespell
  image: grafin1992/nemu-ci:v1.0
  volumes:
  - name: cache
    path: /build

  commands:
  - cd build
  - codespell -q 3 -L 'fo,ser,ans,chello' ../*

  depends_on:
  - cmake

- name: build
  image: grafin1992/nemu-ci:v1.0
  volumes:
  - name: cache
    path: /build

  commands:
  - cd build
  - make

  depends_on:
  - cmake

volumes:
- name: cache
  temp: {}
