language: c
branches:
  only:
    - master
script:
    - mkdir build && cd build
    - cmake ../ -DNM_DEBUG=ON -DNM_SAVEVM_SNAPSHOTS=ON -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON
    - cppcheck --error-exitcode=42 --enable=all ../src
    - make
matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - "sudo apt-get install -qq libgvc6 llibdbus-1-dev ibncursesw5-dev libsqlite3-dev
          libusb-1.0-0-dev libarchive-dev libcgraph6 libudev-dev cppcheck"
