language: c
branches:
  only:
    - master
script:
    - mkdir build && cd build
    - cmake ../ -DNM_SAVEVM_SNAPSHOTS=ON -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON
    - cppcheck --error-exitcode=42 --enable=all --inline-suppr ../src
    - make
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      before_install:
        - >
          sudo apt-get install -qq libdbus-1-dev libncursesw5-dev libsqlite3-dev
          libusb-1.0-0-dev libarchive-dev libgraphviz-dev libudev-dev cppcheck
