name: freebsd

on:
  push:
    branches: [ master ]

jobs:
  freebsd:
    runs-on: [ self-hosted, freebsd-do ]

    steps:
      - uses: actions/checkout@v2

      - name: FreeBSD-13.0 build test
        run: |
          mkdir build && cd build
          cmake ../ -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON
          make
