name: freebsd

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  freebsd:
    runs-on: [ self-hosted, freebsd-do ]

    steps:
      - name: FreeBSD build test
        run: |
          git clone https://github.com/nemuTUI/nemu
          cd nemu
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch origin ${{ github.event.pull_request.head.sha }}:pr
            git switch pr
          fi
          mkdir build && cd build
          cmake ../ -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON
          make
