name: linux

on:
  push:
    branches: [ master ]

jobs:
  linux:
    runs-on: [ self-hosted, linux-do ]
    container: grafin1992/nemu-ci:v1.2

    steps:
      - name: Linux build test
        run: |
          git clone https://github.com/nemuTUI/nemu
          cd nemu && mkdir build && cd build
          cmake -G Ninja ../ \
            -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON
          ninja
